apiVersion: v1
kind: Pod
metadata:
  name: back-demo
  labels:
    app.kubernetes.io/name: "backend"
    app.kubernetes.io/component: "service"
    app.kubernetes.io/version: "v1.0"
spec:
  containers:
    - name: backend-container
      image: nginx:alpine
      ports:
        - containerPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: front-demo
  labels:
    app.kubernetes.io/name: "frontend"
    app.kubernetes.io/component: "service"
    app.kubernetes.io/version: "v1.0"
spec:
  containers:
    - name: frontend-container
      image: nginx:alpine
      ports:
        - containerPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: db-demo
  labels:
    app.kubernetes.io/name: "database"
    app.kubernetes.io/component: "service"
    app.kubernetes.io/version: "v1.0"
spec:
  containers:
    - name: database-container
      image: mysql:5.7
      ports:
        - containerPort: 3306
