apiVersion: v1
kind: Pod
metadata:
  name: demo # this the pod name
spec:
  volumes:
    - name: empty-volume
      emptyDir: {}

  containers:
    - name: demo-container # this is the name of the container
      image: nginx:alpine # this is the image that will be used to create the container
      ports:
        - containerPort: 80 # this is the port that will be exposed by the container
      resources:
        limits:
          memory: "128Mi" # this is the maximum amount of memory that the container can use
          cpu: "500m" # this is the maximum amount of cpu that the container can use
        requests:
          memory: "64Mi" # this is the minimum amount of memory that the container needs to run
          cpu: "250m" # this is the minimum amount of cpu that the container needs to run
      volumeMounts:
        - name: empty-volume
          mountPath: /usr/share/nginx/html
      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 10

    - name: sidecar-container
      image: busybox
      command: ["sh", "-c", "while true; do echo Hello from the sidecar container; sleep 5; done"]
      resources:
        limits:
          memory: "32Mi"
          cpu: "200m"
        requests:
          memory: "16Mi"
          cpu: "110m"
      volumeMounts:
        - name: empty-volume
          mountPath: /data
